### ISSUE TITLE
Priam web app in VPC private subnet is throwing an exception

### ISSUE THREAD

**Issue by johnpyeatt** [Netflix/Priam#211]
I'm trying to run my cassandra 1.2 cluster with the Priam project and when I try to run the .war file in Jetty I get a stack trace. The issue doesn't appear to be a jetty issue, but being caused by the fact that this cassandra node doesn't have a public dns name.

When it starts up it is trying to set the PriamConfiguration.PUBLIC_HOST_NAME by calling http://169.254.169.254/latest/meta-data/public-hostname. But because this node is hidden from the public internet in a private subnet it has no public-hostname, hence the stack trace. I looked at the code for PriamConfiguration.java and the way it is coded there doesn't appear to be any way to override the value with a Priam.properties setting. I suspect the same issue would happen with PriamConfiguration.PUBLIC_IP as well.

Here is a portion of the stack trace for your dining and dancing pleasure. Any help/suggestions would be immensely appreciated.

Caused by: 
org.apache.cassandra.exceptions.ConfigurationException: Unable to get data for URL http://169.254.169.254/latest/meta-data/public-hostname
	at com.netflix.priam.utils.SystemUtils.getDataFromUrl(SystemUtils.java:172)
	at com.netflix.priam.defaultimpl.PriamConfiguration.<init>(PriamConfiguration.java:111)
	at com.netflix.priam.defaultimpl.PriamConfiguration$$FastClassByGuice$$c658aa54.newInstance(<generated>)

**Comment by grecco-gn** [comment]
Hi, 
I was able to get Priam working on a **non-default** but **Internet enabled** VPC by modifying:
priam/src/main/java/com/netflix/priam/aws/AWSMembership.java

The problem was that a security group cannot be referenced directly by name in a non-default VPC but you need to use its group-id. I modified the class to lookup the group id using the provided group name before performing the other requests. 

You can find the changes I made in my fork: 
https://github.com/eg-eng/Priam/commit/429802a977bed255843fb2eba1ebf2060adf778c

Beside that, you need to ensure that you enabled both "DNS Resolution" and "DNS Hostnames" (it defaults to false) on your custom VPC.

As anticipated this, doesn't solve the problem for private VPCs, but it enables you to use Priam in a non-default VPC.
