### ISSUE TITLE
Which version of Priam works with Cassandra 3.x?

### ISSUE THREAD

**Issue by ajaygarga** [Netflix/Priam#540]
Which version of Priam works with Cassandra 3.x?. We plan to use Cassandra 3.x.

**Comment by tulumvinh** [comment]
We have not created Priam for 3.x Cassandra yet.  We will create branch 4.x for Cassandra soon.

**Comment by brange** [comment]
We also plan to use Cassandra 3.x and are wondering what you mean by "soon" :)

**Comment by nirajampac** [comment]
Can I just change the StandardTuner to remove the fields that are not applicable for Cassandra 3.x and make it work ?

**Comment by nirajampac** [comment]
The latest version of cassandra .. Cassandra 3.9 

I changed the standard tuner and removed these fields ... and it seem to work.. But I have issues with the master tag from Friday.. I cannot proceed  because the build is failing .. I opened an issue waiting for some one to pick up and  fix


//map.put("in_memory_compaction_limit_in_mb", config.getInMemoryCompactionLimit());
        //map.put("memtable_total_space_in_mb", config.getMemtableTotalSpaceMB());
        //map.put("multithreaded_compaction", config.getMultithreadedCompaction());

**Comment by bmandrade** [comment]
I was only able to completely build Priam using 3.1.32 version and updating the following:
`gradle/wrapper/gradle-wrapper.properties`:
- `distributionUrl=https\://services.gradle.org/distributions/gradle-3.4.1-all.zip`

`build.gradle`:
- `id 'nebula.netflixoss' version '3.6.0'`

**Comment by vinaykumarchella** [comment]
We have updated build.gradle version with latest netflixoss to fix the issue. And, yes we have tried Priam 3.x branch with C* 3.0.12 and it works fine. Let us know if you run into issues with that.
